CREATE TABLE shortened_urls (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    original_url VARCHAR(500) NOT NULL,
    short_code VARCHAR(10) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
